version: '3.9'

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.3x-ui.rule=Host(${HOSTNAME})"
      - "traefik.http.routers.3x-ui.tls.certresolver=myresolver"
      - "traefik.http.services.3x-ui.loadbalancer.server.port=2053"
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      CONFIG_PORT: ${CONFIG_PORT}
      EMAIL: ${EMAIL}
    ports:
      - "2096:2096"
      - "443:443"
    tty: true
    restart: unless-stopped

  reverse-proxy:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:20657"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=(${EMAIL})"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "${CONFIG_PORT}:20657"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    depends_on:
      - 3x-ui
    restart: unless-stopped

  backend:
    image: torikki/team_418:latest
    environment:
      XUI_LOGIN: ${XUI_LOGIN}
      XUI_PASS: ${XUI_PASS}
      ADMIN_TELEGRAM_ID: ${ADMIN_IDS}
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}